module.exports = {
  PROJECT_TITLE: '区域平台',
  STYLES: {
    DIALOG_WIDTH_MAX: '1298px',
    DIALOG_WIDTH: '800px',
    DIALOG_WIDTH_MIN: '600px',
    DEL_DIALOG_WIDTH: '500px',
    TABLE_HEIGHT: '500px',
    FORM_LABEL_WIDTH: '155px',
    DIALOG_TABLE_HEIGHT: '400PX',
    TABLE_COLUMN_WIDTH: '70',
    TABLE_COLUMN_MIN_WIDTH: '60',
    TABLE_COLUMN_REPORT_WIDTH: '100',
    TABLE_ROW_SELECTED_CLASS: '#E9F3FF'
  },
}
